//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Registration_form.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using Registration_form.CustomValidations;

    public partial class userinfo
    {
        public int ID { get; set; }

        [StringLength(50, MinimumLength = 3, ErrorMessage = "Minimum 3 Characters required")]
        [Required(ErrorMessage = "This Field is required")]
        [RegularExpression(@"^(([A-za-z]+[\s]{1}[A-za-z]+)|([A-Za-z]+))$", ErrorMessage = "Use Lower case and UpperCase Alphabets")]
        public string Name { get; set; }

        [Required(ErrorMessage = "This Field is required")]
        [Range(1, 100)]
        public Nullable<int> Age { get; set; }

        [Required(ErrorMessage = "This Field is required")]
        [City]
        public string City { get; set; }

        [DisplayName("Email-Id")]
        [Required(ErrorMessage = "This Field is required")]
        [RegularExpression(@"\b[\w\.-]+@[\w\.-]+\.\w{2,4}\b", ErrorMessage = "NOt a Vlaid Email-Id")]
        public string Email { get; set; }

        [DisplayName("Mobile Number")]
        [Required(ErrorMessage = "This Field is required")]
        [Phone]
        public string Mobile_no { get; set; }
    }
}
