//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class booking
    {
        public int bookingId { get; set; }
        public int Room_Id { get; set; }
        public System.DateTime bookingDate { get; set; }
        public string statusOfBooking { get; set; }
    }
}
